runner:
  total_steps: 30000
  gradient_clipping: 1
  gradient_accumulate_steps: 8

  log_step: 1000
  eval_step: 1000
  save_step: 1000
  max_keep: 2
  eval_dataloaders:
    - dev
    - test

optimizer:
  name: TorchOptim
  torch_optim_name: Adam
  lr: 1.0e-4

# comment the whole scheduler config block
# to disable learning rate scheduling
# scheduler:
#   name: linear_schedule_with_warmup
#   num_warmup_steps: 1400

downstream_expert:
  datarc:
    root: /home/sharifm/students/zebinyun/fairseq/s3prl/s3prl/IEMOCAP
    pretrain_data: /home/sharifm/students/zebinyun/fairseq/tsv/
    sample_rate: 16000
    label_rate: 50
    label_dir: /home/sharifm/students/zebinyun/fairseq/iter1_k500_label
    meta_data: ./downstream/emotion/meta_data
    test_fold: fold1
    pre_load: True
    train_batch_size: 4
    eval_batch_size: 4
    num_workers: 6
    valid_ratio: 0.2
    max_sample_size: 250000
    min_sample_size: 32000
    pad_audio: false
    normalize: false
    random_crop: true
    max_keep_size: None

  modelrc:
    projector_dim: 256
    select: UtteranceLevel

    UtteranceLevel:
      pooling: MeanPooling

    DeepModel:
      model_type: CNNSelfAttention
      hidden_dim: 80
      kernel_size: 5
      padding: 2
      pooling: 5
      dropout: 0.4
